node(){
  cleanWs()
    stage('check upstream')
            {
                pipelineParams = [:]
                def upstream = currentBuild.rawBuild.getCause(hudson.model.Cause$UpstreamCause)
                triggerCause = upstream?.shortDescription
                println triggerCause
            }

    stage('Do stuff')
            {
                if (triggerCause != null)
                {
                    triggerCause = triggerCause.split()[4].replaceAll('"', '')
                    pipelineParams.put('copy_metadata_from', triggerCause)
                    println triggerCause
                    println pipelineParams
                    def envDir = triggerCause.split('/')[-3].toString().trim()
                    def module = triggerCause.split('/')[-2].toString().trim()
                    def jobName = triggerCause.split('/')[-1].toString().trim()
                    println envDir + " " + module + " " + jobName

                    copyArtifacts projectName: pipelineParams.copy_metadata_from, fingerprintArtifacts: true, flatten: true, filter: 'metadata.json'

                    if (module.equals("Core")){
                        println 'inside if'
                        image_name = sh(returnStdout: true, script: 'jq -r .image_name metadata.json').trim()
                        image_tag = sh(returnStdout: true, script: 'jq -r .image_tag metadata.json').trim()
                        println image_name + " " + image_tag
                    }
                    else
                        println 'inside else'
                    artifact_version = sh(returnStdout: true, script: 'jq -r .artifact_version metadata.json').trim()
                    pipelineParams.put('env', envDir)
                    pipelineParams.put('module', module)
                    pipelineParams.put('jobName', jobName)
                    pipelineParams.put('artifact_version', artifact_version)

                    if (pipelineParams.image_tag == null){
                        sh """
           mkdir -p $JENKINS_HOME/summary/${envDir}
           touch -a $JENKINS_HOME/summary/${envDir}/summary.txt
           sed -i "s/${pipelineParams.jobName}.*//g" $JENKINS_HOME/summary/${envDir}/summary.txt
           sed -i "/^\$/d" $JENKINS_HOME/summary/${envDir}/summary.txt
           echo "${jobName} : ${artifact_version}" >> $JENKINS_HOME/summary/${envDir}/summary.txt
           """
                    }

                    if (pipelineParams.image_tag != null){
                        sh """
           mkdir -p $JENKINS_HOME/summary/${envDir}
           touch -a $JENKINS_HOME/summary/${envDir}/summary.txt
           sed -i "s/${image_name}.*//g" $JENKINS_HOME/summary/${envDir}/summary.txt
           sed -i "/^\$/d" $JENKINS_HOME/summary/${envDir}/summary.txt
           echo "${image_name} : ${image_tag}" >>   $JENKINS_HOME/summary/${envDir}/summary.txt
           """
                    }
                }
                else
                    println "This job can be only triggered from an upstream project"
            }
}
