node(){
 cleanWs()
  stage('check upstream'){
           pipelineParams = [:]
           def upstream = currentBuild.rawBuild.getCause(hudson.model.Cause$UpstreamCause)
           triggerCause = upstream?.shortDescription
           println triggerCause

  }

  stage('tasks'{

    if (triggerCause != null)
 {
           triggerCause = triggerCause.split()[4].replaceAll('"', '')
           pipelineParams.put('copy_metadata_from', triggerCause)
           println triggerCause
           println pipelineParams
           def envDir = pipelineParams.copy_metadata_from.split('/')[-3].trim()
           def module = pipelineParams.copy_metadata_from.split('/')[-2].trim()
           def jobName = pipelineParams.copy_metadata_from.split('/')[-1].trim()      
           println envDir + " " + module + " " + jobName
     
           copyArtifacts projectName: pipelineParams.copy_metadata_from, fingerprintArtifacts: true, flatten: true, filter: 'metadata.json'
  
    if (module == "Summary"){
          println 'inside if'
          image_name = sh(returnStdout: true, script: 'jq -r .image_name metadata.json').trim()
          image_tag = sh(returnStdout: true, script: 'jq -r .image_tag metadata.json').trim()
          println image_name + " " + image_tag
      } 
      else
         {
           println 'inside else'        
           artifact_version = sh(returnStdout: true, script: 'jq -r .artifact_version metadata.json').trim() 
         }
           pipelineParams.put('module', module)
           pipelineParams.put('jobName', jobName)
           pipelineParams.put('artifact_version', artifact_version)
           pipelineParams.put('image_name', image_name)
           pipelineParams.put('image_tag', image_tag
    
   
    if (pipelineParams.image_tag == null){
        sh """
           mkdir -p $JENKINS_HOME/summary/${envDir}
           touch -a $JENKINS_HOME/summary/${envDir}/summary.txt
           sed -i "s/${pipelineParams.jobName}.*//g" $JENKINS_HOME/summary/${pipelineParams.env}/summary.txt
           sed -i "/^\$/d" $JENKINS_HOME/summary/${pipelineParams.env}/summary.txt
           echo "${pipelineParams.jobName} : ${pipelineParams.artifact_version}" >> $JENKINS_HOME/summary/${pipelineParams.env}/summary.txt
           """
      }
    
    if (pipelineParams.image_tag != null){
        sh """
           mkdir -p $JENKINS_HOME/summary/${envDir}
           touch -a $JENKINS_HOME/summary/${envDir}/summary.txt
           sed -i "s/${pipelineParams.image_name}.*//g" $JENKINS_HOME/summary/${pipelineParams.env}/summary.txt
           sed -i "/^\$/d" $JENKINS_HOME/summary/${pipelineParams.env}/summary.txt
           echo "${pipelineParams.image_name} : ${pipelineParams.image_tag}" >>   $JENKINS_HOME/summary/${pipelineParams.env}/summary.txt
           """
     }
}
else 
	println "This job can be only triggered from an upstream project"
}
}
